[project]
name = "online-ordering"
version = "0.1.0"
description = "An online food ordering API."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pre-commit>=4.2.0",
    "ruff>=0.12.5",
    "uvicorn>=0.35.0",
]
